// Frontend configuration
// This file is auto-generated by docker-entrypoint.sh at container startup
// Override API_BASE_URL via environment variable when deploying
window.APP_CONFIG = {
    API_BASE_URL: ""
};
